package model

// SignalType represents the direction of a trading signal.
type SignalType int8

const (
	// NoSignal indicates no actionable signal.
	NoSignal SignalType = iota
	// Buy indicates a long entry signal.
	Buy
	// Sell indicates a short entry signal.
	Sell
)

// String returns the human-readable name of the signal type.
func (s SignalType) String() string {
	switch s {
	case Buy:
		return "BUY"
	case Sell:
		return "SELL"
	default:
		return "NO_SIGNAL"
	}
}

// Signal represents a trade signal generated by a strategy.
// It carries the signal metadata but does NOT trigger execution directly.
// All signals must pass through the Risk Engine before order submission.
type Signal struct {
	Type        SignalType // Signal direction
	Symbol      string    // Currency pair
	Price       float64   // Price at signal generation
	Strength    float64   // Signal confidence/strength [0.0, 1.0]
	StopLoss    float64   // Suggested stop-loss price (0 if unset)
	TakeProfit  float64   // Suggested take-profit price (0 if unset)
	TimestampNs int64     // Generation time as Unix nanoseconds
	StrategyID  string    // Identifier of the generating strategy
}

// IsActionable returns true if the signal carries a directional trade intent.
func (s Signal) IsActionable() bool {
	return s.Type == Buy || s.Type == Sell
}
